### ISSUE TITLE
Not ES5 compatible 

### ISSUE THREAD

**Issue by flybayer** [blitz-js/superjson#62]
I'm getting the following error in my app. superjson should be es5 compatible since that's what most libraries do.

```
TypeError: Object doesn't support property or method 'fromEntries'
  at plainer(/opt/render/project/src/node_modules/superjson/dist/superjson.esm.js:909:3)
  at N(/opt/render/project/src/node_modules/superjson/dist/superjson.esm.js:971:7)
  at getQuery
```

We also had this issue in blitz core. We switched to use lodash.fromPairs. See these TSDX instructions for how to use lodash properly: https://tsdx.io/optimization#using-lodash.

Also, we should add eslint rules to prevent this in the future. We are doing this in Blitz with https://github.com/blitz-js/blitz/pull/1124 and https://github.com/blitz-js/blitz/pull/1129

**Comment by markhughes** [comment]
FYI this was reverted in https://github.com/blitz-js/superjson/commit/16cae250549e4822a22a014bb96597468dfff33f#diff-df7446068188621a3fa66e02d4e5c9081902f1bb2cd9092e06c59271978257d3L294-R297 by @Skn0tt

**Comment by markhughes** [comment]
For others, my temporary hack is this :


```
const fromPairs = (arr) => arr.reduce((acc, val) => (acc[val[0]] = val[1], acc), {})
var simpleRulesByAnnotation = fromPairs(simpleRules.map(function (r) { return [r.annotation, r]; }));
```

For those getting "Object.fromEntries is not a function" with blitz in some browsers. :)

**Comment by Skn0tt** [comment]
Thanks for reporting the regression! Will be fixed in #110.

@allcontributors add markhughes for bug

**Comment by markhughes** [comment]
@Skn0tt great work!
